### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by Tom-Finke** [justanoobcoder/eww#1]
Hi there,

I switched to DWM yesterday and wanted to get an eww bar to work. I stumbled upon your repo. I have a couple of issues setting things up.

1. The `dwm-dump-all` Script is a binary File which makes me kinda not want to execute it because I have no idea what is going on

2. DWM Tag fetching does not seem to work. dwm-tags Script was complaining that there is no /tmp/dwm.log. I tried just starting dwm with `dwm > /tmp/dwm.log` but this does not do the trick. How do you get dwm to log to `/tmp/dwm.log` (also, wouldn't `/var/log` make more sense?)
3.  What Font do you use for Status icons like RAM and Battery?

Other than that, thanks for making your config public. Do you have any tipps on how to get started with eww + dwm?

**Comment by justanoobcoder** [comment]
Hi there, it's kinda tricky to get eww work with dwm.

Firstly, I will show you how this eww look like:
![image](https://github.com/justanoobcoder/eww/assets/57614330/930deb11-e0bf-4c54-ad61-582a8fad796f)
About the issues:
1. The purpose of `dwm-dump-all` is to get dwm current state information like available tags, current active tag, layout,...:
![image](https://github.com/justanoobcoder/eww/assets/57614330/aec4b52a-c6a6-411a-ae7e-232cedbf8a2d)
This script is used in `dwm-layout` script to get current layout symbol (eg: []= in the first image). It's also used in `dwm-tags.py` script to get tags info, then create an eww component.
![image](https://github.com/justanoobcoder/eww/assets/57614330/bec8c8da-ca84-4c7a-b3fb-ff56c3224d97)
2. To make eww work with dwm, you need some patches for dwm. The first one is [ipc](http://dwm.suckless.org/patches/ipc/), this patch exposes dwm information through a cli program named `dwm-msg`  (this cli will be generated with dwm when you compile dwm after ipc patch applied). The second patch is [anybar](http://dwm.suckless.org/patches/anybar/). This patch will allow dwm to use external bar like eww, you need to change `altbarclass` to `Eww` in `config.h` or `config.def.h`. The last one is [autostart](http://dwm.suckless.org/patches/autostart/). This patch will run startup script `~/.local/share/dwm/autostart.sh` before running dwm. You can put eww startup command here. I use `/tmp/dwm.log` because it does not require root access. Plus, the log file just contains dwm current state info for eww, it's overrided everytime dwm state change, which means they're temporary info, so put it in `/tmp` make more sense.
3. To use this eww, you need 3 fonts: Comic Mono (for clock component), Noto Sans CJK (for dwm tags name) and Font Awesome 6 Pro (for icons)

For references, you can take a look at these:
- [My autostart.sh script](https://github.com/justanoobcoder/dotfiles/tree/main/.local/share/dwm)
- [My dwm repo](https://github.com/justanoobcoder/dwm)

Hope this would help. Oh, one more thing, my screen resolution is 1366x768 so this eww bar might look different on other resolutions

**Comment by Tom-Finke** [comment]
Thanks for the really fast reply.

I figured that I needed ipc and anybar and managed to set them up already. I was missing autostart and in particular the ` dwm-msg subscribe` part. 

Do you have the source of the `dwm-dump-all` script?

**Comment by justanoobcoder** [comment]
The `dwm-dump-all` came from [this](https://github.com/mihirlad55/dwmipcpp) repo. It's a client that can communicate with ipc-patched dwm. You can clone it, run `./build.sh`. The script is `build/examples/dump-all` after the compilation.
